apiVersion: v1
entries:
  alpha-functions-backend:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-01-25T13:12:55.567442+05:30"
    description: A Helm chart for Kubernetes
    digest: 9c0fb816b600a27c7e0effb2beaffcc8a058c7393db1aa48ba70c46328455ec1
    name: alpha-functions-backend
    type: application
    urls:
    - https://kabirnarang39.github.io/alpha-functions/alpha-functions-deployment/helm/alpha-functions-backend/charts/alpha-functions-backend-0.1.0.tgz
    version: 0.1.0
generated: "2025-01-25T13:12:55.563712+05:30"
