apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alpha-functions-frontend.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "alpha-functions-frontend.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "alpha-functions-frontend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "alpha-functions-frontend.name" . }}
    spec:
      containers:
        - name: alpha-functions-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            {{- if .Values.env }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
