image:
  repository: kabirnarang39/alpha-functions-frontend
  tag: latest
  pullPolicy: Always

replicaCount: 1

namespace: alphafunctions

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

env:
  NODE_ENV: "production"
  REACT_APP_ALPHA_FUNCTIONS_BACKEND_URL: "http://alpha-functions-frontend-alpha-functions-frontend"
  DEBUG: "false"